services:
  - type: web
    name: global-price-scraper
    env: ruby
    plan: starter
    buildCommand: bundle install
    startCommand: bundle exec rackup -o 0.0.0.0 -p $PORT
    envVars:
      - key: RACK_ENV
        value: production
      - key: SERPAPI_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: EANSEARCH_API_KEY
        sync: false
